services:
  onlyoffice-documentserver:
    networks:
      default:
      artcoded:
    build:
      context: .
    image: onlyoffice/documentserver #[-de,-ee]
    container_name: onlyoffice-documentserver
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      # Uncomment strings below to enable the JSON Web Token validation.
      - JWT_ENABLED=true
      - JWT_SECRET=QlfCe9hMhkD7K6NWKfHScWXMGX7n4Hf07TCKRLNo8n+zvrJaXzRQUuTel6yGnfij
      - JWT_HEADER=Authorization
      - JWT_IN_BODY=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/info/info.json"]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 10s
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
       - ./data/onlyoffice/data:/var/www/onlyoffice/Data
       - ./data/onlyoffice/logs:/var/log/onlyoffice
       - ./data/onlyoffice/cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
       - ./data/onlyoffice/examples:/var/www/onlyoffice/documentserver-example/public/files
       - /./data/onlyoffice/fonts:/usr/share/fonts
       
  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq:3
    restart: always
    networks:
      default:
    expose:
      - '5672'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 10s

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:15
    networks:
      default:
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onlyoffice"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 10s
networks:
  artcoded:
    name: custom_network
    external: true

